### ISSUE TITLE
Undefined class constant 'SHARE_TYPE_REMOTE_GROUP'

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/oc-opencloudmesh#10]
This is probably because I'm mounting the wrong version of the code somehow, investigating.

**Comment by michielbdejong** [comment]
Trace:
```
#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Share20\\\/Manager.php(159):
OCA\\\\OpenCloudMesh\\\\ShareProviderFactory->getProviderForType()\\n

#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Share20\\\/Manager.php(1422): 
OC\\\\Share20\\\\Manager->shareTypeToProviderMap()\\n

#2 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/MountProvider.php(71): 
OC\\\\Share20\\\\Manager->getAllSharedWith()\\n

#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(82): 
OCA\\\\Files_Sharing\\\\MountProvider->getMountsForUser()\\n

#4 [internal function]: 
OC\\\\Files\\\\Config\\\\MountProviderCollection->OC\\\\Files\\\\Config\\\\{closure}(*** sensitive parameters replaced ***)\\n

#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(83): 
array_map()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Filesystem.php(445): OC\\\\Files\\\\Config\\\\MountProviderCollection->getMountsForUser()\\n

#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Cache\\\/File.php(51): 
OC\\\\Files\\\\Filesystem::initMountPoints()\\n

#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Cache\\\/File.php(172):
 OC\\\\Cache\\\\File->getStorage()\\n

#9 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(747): OC\\\\Cache\\\\File->gc()\\n

#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Hooks\\\/EmitterTrait.php(98): OC::{closure}(*** sensitive parameters replaced ***)\\n

#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Hooks\\\/PublicEmitter.php(33): OC\\\\Hooks\\\\BasicEmitter->emit()\\n

#12 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(1026): OC\\\\Hooks\\\\PublicEmitter->emit()\\n

#13 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(542): OC\\\\User\\\\Session->loginInOwnCloud()\\n

#14 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/User\\\/Session.php(343): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n

#15 \\\/var\\\/www\\\/html\\\/core\\\/Controller\\\/LoginController.php(270): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n

#16 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n

#17 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n

#18 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n

#19 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n

#20 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n

#21 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n

#22 \\\/var\\\/www\\\/html\\\/index.php(54): OC::handleRequest()\\n

#23 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/oc-opencloudmesh\\\/opencloudmesh\\\/lib\\\/ShareProviderFactory.php\",\"Line\":114}"}

**Comment by michielbdejong** [comment]
It seems indeed that https://github.com/pondersource/oc-opencloudmesh/blob/894ec49/opencloudmesh/lib/ShareProviderFactory.php#L114 refers to this class constant
And this constant exists in https://github.com/pondersource/core/blob/a1e761e/lib/private/Share/Constants.php#L34
But we weren't mounting the `lib` folder from owncloud into the container!
