### ISSUE TITLE
owncloud files app shows no files with accept-ocm-to-groups branch and this app not installed

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/oc-opencloudmesh#19]
If they merge our accept-ocm-to-groups branch then it would break the Files app for everyone who does not install our opencloudmesh app. It will look like this:
<img width="1121" alt="Screenshot 2023-06-22 at 14 09 55" src="https://github.com/pondersource/oc-opencloudmesh/assets/408412/f46847c1-0303-48df-b581-521b58526f5f">

**Comment by navid-shokri** [comment]
the error is : 
```
{"reqId":"LCnhhVmhRFgTrcI63GEN","level":4,"time":"2023-06-25T13:35:07+00:00","remoteAddr":"172.18.0.2","user":"einstein",
"app":"webdav","method":"PROPFIND","url":"\/remote.php\/dav\/files\/einstein\/",
"message":"Exception: No share provider for share type 7: 
{\"Exception\":\"OC\\\\Share20\\\\Exception\\\\ProviderException\",\"Message\":\"No share provider for share type 7\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Share20\\\/Manager.php(160): OC\\\\Share20\\\\ProviderFactory->getProviderForType()\\n
#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Share20\\\/Manager.php(1272): OC\\\\Share20\\\\Manager->shareTypeToProviderMap()\\n
#2 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(146): OC\\\\Share20\\\\Manager->getAllSharesBy()\\n
#3 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(197): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->getSharesForNodeIds()\\n
#4 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->handleGetProperties()\\n
#5 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1052): Sabre\\\\DAV\\\\Server->emit()\\n
#6 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(984): Sabre\\\\DAV\\\\Server->getPropertiesByNode()\\n
#7 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1662): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath()\\n
#8 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1642): Sabre\\\\DAV\\\\Server->writeMultiStatus()\\n
#9 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Sapi.php(83): Sabre\\\\DAV\\\\Server->Sabre\\\\DAV\\\\{closure}(*** sensitive parameters replaced ***)\\n
#10 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(490): Sabre\\\\HTTP\\\\Sapi::sendResponse()\\n
#11 \\\/var\\\/www\\\/html\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n
#12 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(348): Sabre\\\\DAV\\\\Server->start()\\n
#13 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n
#14 \\\/var\\\/www\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n
#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Share20\\\/ProviderFactory.php\",\"Line\":138}"}
```

**Comment by navid-shokri** [comment]
So We discussed this patch and decided to continue with this approach
