### ISSUE TITLE
unable to disable opencloudmesh app by occ command

### ISSUE THREAD

**Issue by navid-shokri** [pondersource/oc-opencloudmesh#25]
when I want to disable the app by occ Command I am encountering with this error: 

> sudo -u www-data php occ app:disable opencloudmesh

```
Xdebug: [Log Files] File '/var/www/html/xdebug.log' could not be opened.
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
An unhandled exception has been thrown:
Error: Class 'OCA\FederatedGroups\ShareProviderFactory' not found in /var/www/html/lib/private/Server.php:903
Stack trace:
#0 /var/www/html/lib/composer/pimple/pimple/src/Pimple/Container.php(122): OC\Server->OC\{closure}()
#1 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(107): Pimple\Container->offsetGet()
#2 /var/www/html/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query()
#3 /var/www/html/lib/private/Server.php(1678): OC\ServerContainer->query()
#4 /var/www/html/apps/files_sharing/lib/AppInfo/Application.php(167): OC\Server->getShareManager()
#5 /var/www/html/lib/composer/pimple/pimple/src/Pimple/Container.php(122): OCA\Files_Sharing\AppInfo\Application->OCA\Files_Sharing\AppInfo\{closure}()
#6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(107): Pimple\Container->offsetGet()
#7 /var/www/html/apps/files_sharing/lib/AppInfo/Application.php(209): OC\AppFramework\Utility\SimpleContainer->query()
#8 /var/www/html/apps/files_sharing/appinfo/app.php(38): OCA\Files_Sharing\AppInfo\Application->registerMountProviders()
#9 /var/www/html/lib/private/legacy/app.php(253): require_once('/var/www/html/a...')
#10 /var/www/html/lib/private/legacy/app.php(192): OC_App::requireAppFile()
#11 /var/www/html/lib/private/legacy/app.php(125): OC_App::loadApp()
#12 /var/www/html/lib/private/Console/Application.php(103): OC_App::loadApps()
#13 /var/www/html/console.php(115): OC\Console\Application->loadCommands()
#14 /var/www/html/occ(11): require_once('/var/www/html/c...')
#15 {main}root@5eae60babb19:/var/www/html# sudo -u www-data php occ app:disable opencloudmesh 
Xdebug: [Log Files] File '/var/www/html/xdebug.log' could not be opened.
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
An unhandled exception has been thrown:
Error: Class 'OCA\FederatedGroups\ShareProviderFactory' not found in /var/www/html/lib/private/Server.php:903
Stack trace:
#0 /var/www/html/lib/composer/pimple/pimple/src/Pimple/Container.php(122): OC\Server->OC\{closure}()
#1 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(107): Pimple\Container->offsetGet()
#2 /var/www/html/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query()
#3 /var/www/html/lib/private/Server.php(1678): OC\ServerContainer->query()
#4 /var/www/html/apps/files_sharing/lib/AppInfo/Application.php(167): OC\Server->getShareManager()
#5 /var/www/html/lib/composer/pimple/pimple/src/Pimple/Container.php(122): OCA\Files_Sharing\AppInfo\Application->OCA\Files_Sharing\AppInfo\{closure}()
#6 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(107): Pimple\Container->offsetGet()
#7 /var/www/html/apps/files_sharing/lib/AppInfo/Application.php(209): OC\AppFramework\Utility\SimpleContainer->query()
#8 /var/www/html/apps/files_sharing/appinfo/app.php(38): OCA\Files_Sharing\AppInfo\Application->registerMountProviders()
#9 /var/www/html/lib/private/legacy/app.php(253): require_once('/var/www/html/a...')
#10 /var/www/html/lib/private/legacy/app.php(192): OC_App::requireAppFile()
#11 /var/www/html/lib/private/legacy/app.php(125): OC_App::loadApp()
#12 /var/www/html/lib/private/Console/Application.php(103): OC_App::loadApps()
#13 /var/www/html/console.php(115): OC\Console\Application->loadCommands()
#14 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

**Comment by navid-shokri** [comment]
I found the reason, in the previous step I removed the `federatedgroups` App and I did not remove its configuration from config/config.php. So it caused this error.
